// Code generated by goctl. DO NOT EDIT.
package types

type SendCodeRequest struct {
	Phone string `json:"phone"`
}

type WxLoginRequest struct {
	Code string `json:"code"`
}

type PhoneLoginRequest struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
	Key   string `json:"key"`
}

type EditUserInfoRequest struct {
	UserId   int64  `json:"-"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int    `json:"gender"`
	Province string `json:"province"`
	City     string `json:"city"`
}

type AddAddressRequest struct {
	UserId   int64  `json:"-"`
	PostCode string `json:"postCode"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Province string `json:"province"`
	City     string `json:"city"`
	District string `json:"district"`
	Address  string `json:"address"`
	Default  bool   `json:"default"`
}

type SendCodeResponse struct {
	Key string `json:"key"`
}

type LoginResponse struct {
	UserInfo UserInfoResponse `json:"userInfo"`
	Token    string           `json:"token"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int    `json:"gender"`
	Phone    string `json:"phone"`
	Province string `json:"province"`
	City     string `json:"city"`
}
